##Introduction to Object Oriented Programming(OOP's)-Python
One of the popular approach to slove a programming problem by creating an objects.This is known as Object Oriented Programming.

#An object has own charactersitics:
1.Attributes(name,age,colour)
2.Behaviour(learn,study,singing,dance)

#in Python,the concept oop follow these things:
1.Inheritance
2.Encapsulation
3.Polymorphise

#class:class is the blueprint of the Object
#Object:Blueprint of class or instance 

class classname:
    #some function and variables
    #Function-used to perform a specific activity
    #variables-Data (memory)

In [8]:
def test():
    print("test() for function")
    return
test()

test() for function


In [7]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()

test() for the class and method


In [28]:
#Factorial of a number
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
print(p1.fact(5))

120


In [ ]:
class Demo2()
    def Accepr(self,p1,p2)
        a=p1
        b=p2
        return
    def display(self)
        print("p1=",p1)
        print("p2=",p2)
c1=Demo2()
c1.accept(10,20)
c1.display()

In [30]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
    
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [37]:
import re
sum=0
pattern='back'
if re.match(pattern,'backup.txt'):
    sum+=1
if re.match(pattern,'text.back'):
    sum+=2
if re.search(pattern,'backup.txt'):
    sum+=4
if re.search(pattern,'text.back'):
    sum+=8
print(sum)

13


In [41]:
#some Inheritance
#Parent class
class Person(object):
    #Constructor
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False

#Derived Class
class Employee(Person):
    def isEmployee(self):
        return True

emp=Person("Anil")
print(emp.getName(),emp.isEmployee())

emp1=Employee("Akhil")
print(emp1.getName(),emp1.isEmployee())

Anil False
Akhil True


Python Numpy:
Numpy arrays is a bit like python List
Numpy array is a central data structure of the numpy lib
This lib actually short for"Numeris Python" or "Numerical Python"


In [42]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [49]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [50]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [51]:
lst=[1.0,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [57]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [58]:
#Re-shape the given array
#numpy.reshape(arrayName,reshape,order='C')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
print(a1.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [63]:
#Append data--Horizontally
#Append data--Vertically

a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [65]:
#Append some data--vertical
#vstack(array1,array2)--will be automatically arranged in vertical
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [66]:
#generate random numbers from NP
a1=np.random.normal(5,0.5,10)
print(a1)

[5.91911118 4.81551465 5.44851574 4.83681128 4.34442148 4.91975184
 5.53405775 5.45152074 4.48137123 5.52699422]


In [68]:
#numpy.zeros() and numpy.one()
#generate an array with all zeroes--numpy.zeros()
#numpy.zeros(shape,dtype=float,order='C')
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [72]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [73]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [74]:
#np.ones(shape,dtype=float,order='C')
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [76]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [77]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [79]:
#arrange()--particular
#numpy,arrange(start,end,stop)
#start-Value
#end=Value
#step-Gap between one value to another value

import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
# Indexing and slicing of numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [83]:
a1=np.array([(1,2,3),(4,5,6)])
print("First Row:",a1[0])

First Row: [1 2 3]


In [84]:
a1=np.array([(1,2,3),(4,5,6)])
print("Second Row:",a1[1])

Second Row: [4 5 6]


In [85]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Column:",a1[:,1])

Slicing Column: [2 5]


In [86]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Last Column:",a1[:,2])

Slicing Last Column: [3 6]


In [87]:
a1=np.array([(1,2,3),(4,5,6)])
print("Row and Column:",a1)

Row and Column: [[1 2 3]
 [4 5 6]]


In [88]:
a1=np.random.normal(5,1,10)
print(a1)

[4.88304167 2.9856659  4.13771394 6.2576296  4.65880988 5.41348411
 4.87743448 4.68013698 4.21423445 5.6710746 ]


In [94]:
#Some math Operation on givenrandom numbers
#Min--returns the least number
#Max--returns the least numbers
#Mean--Mean
#Median--Median
a1=np.random.normal(5,1,10)
print(a1)
print("Min Value=",np.min(a1))
print("Max Value=",np.max(a1))
print("Mean Value=",np.mean(a1))
print("Median Value=",np.median(a1))  

[6.01519881 4.85766913 4.53473422 3.26088189 5.73082047 6.01924804
 5.22648704 4.88141478 6.8986727  6.00377567]
Min Value= 3.2608818896162517
Max Value= 6.898672701334526
Mean Value= 5.342890274624251
Median Value= 5.478653756524763


In [95]:
#Multiply of ID arrays
#numpy.dot(x,y)---
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [96]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [99]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

In [103]:
class test:
    def __init__(self,a):
        self.a=a

    def display(self):
        print(self.a)
obj=test()
obj.display()

TypeError: __init__() missing 1 required positional argument: 'a'

In [107]:
class foo:
    def printline(self,line='python'):
        print(line)

o1=foo()
o1.printline('java')

java


In [109]:
import numpy as np
a=np.array([1,2,3,5,8])
b=np.array([0,3,4,2,1])
c=a+b
c=c*a
print(c[2])

21


##Pandas basics:
###pandas,dataframes
####data analysis with python

#Python is one of the popular programming language for data analysis <br>
#Python is offering the lib called pandas used for importing and analyzingpretty much faster and easier also
PandasDataFramesDataAnalysis with Python

In [1]:
import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],"EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],"MobileNumber":[999,888,777,888,777,999],"Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"]}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID  MobileNumber Address
0    Anil    anil@gmail.com           999     Hyd
1   Akhil   akhil@gmail.com           888     Hyd
2  Dinesh  dinesh@gmail.com           777     Hyd
3  Harsha  harsha@gmail.com           888     Hyd
4    Ajay    ajay@gmail.com           777     Hyd
5  Kranth  kranth@gmail.com           999     Hyd


In [2]:
b.index=["01","02","03","04","05","06"]
print(b)

      Name           EmailID  MobileNumber Address
01    Anil    anil@gmail.com           999     Hyd
02   Akhil   akhil@gmail.com           888     Hyd
03  Dinesh  dinesh@gmail.com           777     Hyd
04  Harsha  harsha@gmail.com           888     Hyd
05    Ajay    ajay@gmail.com           777     Hyd
06  Kranth  kranth@gmail.com           999     Hyd


In [12]:
def frequncy(a):
    i=0
    while(i<=9):
        count=0
        for j in range(len(a)):
            if (ord(a[j])>=48 and ord(a[j])<=56):
                if i==int(a[j]):
                    count=count+1
        print(count,end=" ")
        i=i+1
a="213abc456def111"
frequncy(a)

0 4 1 1 1 1 1 0 0 0 

In [13]:
def check(s1, s2): 
      
    # the sorted strings are checked  
    if(sorted(s1)== sorted(s2)): 
        print("The strings are anagrams.")  
    else: 
        print("The strings aren't anagrams.")          
          
# driver code   
s1 ="listen"
s2 ="silent" 
check(s1, s2) 

The strings are anagrams.
